### ISSUE TITLE
Adapt to macOS & remove dependency of `requests`

### ISSUE THREAD

**Issue by nicognaW** [ocodo/ollama_zsh_completion#10]
Thanks for your work on this repo, it helped me a lot! But when I used the plugin in macOS, I encountered two problems and I tried to [patch](https://github.com/nicognaW/ollama_zsh_completion/commit/aacc3b8f101a04aed5143ed397c77197363bf224) them.

1. using stat in macOS to get the last modification time should be done with the command `stat -f %m`.
2. `fetch_ollama_library_models` uses `requests` for sending HTTP requests and my global python interpreter doesn't have it installed so I used `urllib.requests` from the standard library in my patch.

I'm not sure if these changes are safe or suitable to start a PR, so I've kept them in my [fork](https://github.com/nicognaW/ollama_zsh_completion) for now.

**Comment by jasonm23** [comment]
Thank you, it looks like it should be ok as a PR.  

I don't have a Macos instance to test with myself, so perhaps just keep an eye on it and submit as a PR when you are confident that it's usable there.

All assuming this is going to be more broadly compatible than using `requests`.

**Comment by jasonm23** [comment]
(usable and won't impact any other platforms/oses)

**Comment by jasonm23** [comment]
This may be relevant:

> WIth macOS 12.3, Apple removed the deprecated Python 2.7.16 distribution and from future releases of macOS. Apple rewrote in Swift, those parts of the operating system that previously required Python support.

>  Unless you plan to write code in Python3, you do not need to install it.

> If you have installed the current Command Line Tools for Xcode 15, or Xcode 15 itself, then either installation will install the quite outdated Python 3.9.6. Again, if you do not plan to write Python3 code, just ignore its presence after either of these two installations.

Which begs the question, which version of Macos are you using and which version of Python is installed?

**Comment by nicognaW** [comment]
I'm using 15.1.1 which is the latest macOS at the time, and Python 3.13 provided by homebrew. Most devs with Mac should have the XCode Command Line Tools installed, recent versions of the tools provide Python 3.9.6.

Python versions shouldn't be a problem since `urllib.request` is introduced in 3.0.

**Comment by jasonm23** [comment]
Right, but 'requests' is in core from 3.7 

So am I missing something or is my info just wrong about 3.7?

**Comment by nicognaW** [comment]
afaik, 'requests' is a third party library and is never included in standard python

**Comment by jasonm23** [comment]
@nicognaW that'd certainly clear up the issue.  Ok, I'll check #11 again and continue the convo there.
